### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by rustkas**
- Documentation generation
  - Add settings and make changes to generate public and private EDoc.
  - Tune documentation content for highlighting important words and sentences.
- README.md
  - Tune list of badges.

### CODE REVIEW

**Comment by mworrell** [comment]
@mmzeeman Would it be ok to ask @rustkas to remove 19, 20, and 21 from the tests?

**Comment by rustkas** [comment]
> @mmzeeman Would it be ok to ask @rustkas to remove 19, 20, and 21 from the tests?

No problem. I will do it.

**Comment by mmzeeman** [comment]
Those are kind of obsolete indeed.

**Comment by rustkas** [comment]
Maybe add 24, 25 OTP versions? What you (@mworrell, @mmzeeman) think?

**Review by mmzeeman — APPROVED** [review]

**Comment by mmzeeman** [comment]
Oh, @rustkas, the indentation of the newly added rules in the Makefile at line 33 and the one below it needs to be a tab, instead of spaces.

**Comment by rustkas** [comment]
> Oh, @rustkas, the indentation of the newly added rules in the Makefile at line 33 and the one below it needs to be a tab, instead of spaces.

Yes. I noticed. Corrected.

**Comment by mmzeeman** [comment]
Thanks 🎉

**Pull request merged**
